/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory.Salles;

//import org.apache.pdfbox.io.RandomAccessRead;
import com.inventory.Database.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class DataDetail extends javax.swing.JPanel {

    Connection conn = null;

    PreparedStatement prepStatement = null;
    Statement statement = null;
    ResultSet resultSet = null;
    Date tanggal = new Date();

    public DataDetail() {
        initComponents();
        try {
            conn = new ConnectionFactory().getConn();
            statement = conn.createStatement();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        p_notifikasi.hide();
        totalPenjualan();
        totalKeuntungan();
        totalProduk();
        notifikasi();
        stok();
        terlaris();
        tampilLaporan();
        totalPendapatan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalBarang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lb_totalTodaySales = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb_totalTodayBenefice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lb_totalProduct = new javax.swing.JLabel();
        p_notifikasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_caristok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_stok = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_favorit = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_laporan = new javax.swing.JTable();
        txt_terlaris = new javax.swing.JTextField();
        btn_cariterlaris = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lb_TotalRevenue = new javax.swing.JLabel();

        totalBarang.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        totalBarang.setForeground(new java.awt.Color(255, 255, 255));
        totalBarang.setText("0");
        totalBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Banyak Barang");

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(210, 218, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Les Information sur le vende Aujourd'huit");

        jPanel2.setBackground(new java.awt.Color(245, 235, 224));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("nombre de vente aujourduit");

        lb_totalTodaySales.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        lb_totalTodaySales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_totalTodaySales.setText("0");
        lb_totalTodaySales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_totalTodaySales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lb_totalTodaySales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(245, 235, 224));

        lb_totalTodayBenefice.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        lb_totalTodayBenefice.setText("0");
        lb_totalTodayBenefice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Today's Profit");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Rp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_totalTodayBenefice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_totalTodayBenefice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(29, 29, 29))
        );

        jPanel4.setBackground(new java.awt.Color(245, 235, 224));

        jLabel10.setText("produit peux vender");

        lb_totalProduct.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        lb_totalProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_totalProduct.setText("0");
        lb_totalProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_totalProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_totalProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(30, 30, 30))
        );

        p_notifikasi.setBackground(new java.awt.Color(255, 0, 0));
        p_notifikasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        p_notifikasi.setForeground(new java.awt.Color(255, 255, 255));
        p_notifikasi.setPreferredSize(new java.awt.Dimension(900, 56));
        p_notifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_notifikasiMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Attention !! il existe dans le stoque des produit inverieur a 3");

        javax.swing.GroupLayout p_notifikasiLayout = new javax.swing.GroupLayout(p_notifikasi);
        p_notifikasi.setLayout(p_notifikasiLayout);
        p_notifikasiLayout.setHorizontalGroup(
            p_notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_notifikasiLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_notifikasiLayout.setVerticalGroup(
            p_notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txt_stok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_stok.setText("3");

        jLabel4.setText("produit inverieur de:");

        btn_caristok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caristokActionPerformed(evt);
            }
        });

        tb_stok.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tb_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tb_stok);

        jLabel5.setText("Produit favoriser");

        tb_favorit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tb_favorit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tb_favorit);

        jLabel6.setText("vent aujourd'hui");

        tb_laporan.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tb_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(tb_laporan);

        txt_terlaris.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_terlaris.setText("5");

        btn_cariterlaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariterlarisActionPerformed(evt);
            }
        });

        jLabel11.setText("line:");

        jPanel5.setBackground(new java.awt.Color(0, 204, 0));
        jPanel5.setMaximumSize(new java.awt.Dimension(899, 87));
        jPanel5.setMinimumSize(new java.awt.Dimension(899, 87));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel12.setText("Today's Total Revenue : Rp");

        lb_TotalRevenue.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lb_TotalRevenue.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_TotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lb_TotalRevenue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_stok, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_caristok, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_terlaris, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_cariterlaris, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(p_notifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_notifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cariterlaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(txt_terlaris)
                            .addComponent(txt_stok, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(btn_caristok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void p_notifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_notifikasiMouseClicked
        p_notifikasi.hide();
    }//GEN-LAST:event_p_notifikasiMouseClicked

    private void btn_cariterlarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariterlarisActionPerformed
        terlaris();
    }//GEN-LAST:event_btn_cariterlarisActionPerformed

    private void btn_caristokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caristokActionPerformed
        stok();
    }//GEN-LAST:event_btn_caristokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caristok;
    private javax.swing.JButton btn_cariterlaris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_TotalRevenue;
    private javax.swing.JLabel lb_totalProduct;
    private javax.swing.JLabel lb_totalTodayBenefice;
    private javax.swing.JLabel lb_totalTodaySales;
    private javax.swing.JPanel p_notifikasi;
    private javax.swing.JTable tb_favorit;
    private javax.swing.JTable tb_laporan;
    private javax.swing.JTable tb_stok;
    private javax.swing.JLabel totalBarang;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_terlaris;
    // End of variables declaration//GEN-END:variables
 private void totalProduk() {
        try {
            String Produk = "SELECT COUNT(*) AS nmbrPrd \n"
                    + "FROM products \n"
                    + "WHERE quantity > 0;";
            resultSet = statement.executeQuery(Produk);
            if (resultSet.next()) {
                lb_totalProduct.setText(Integer.toString(resultSet.getInt(1)));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "di cek Kembali " + e + "");
        }
    }

    private void notifikasi() {
        try {
            String Produk = "SELECT quantity FROM products ";
            resultSet = statement.executeQuery(Produk);

            while (resultSet.next()) {
                int stok = resultSet.getInt(1);
                if (stok < 3) {
                    p_notifikasi.setVisible(true);
                }
            }

            // Menutup koneksi ke database
//            result.close();
//            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cek kembali: " + e.getMessage());
        }
    }

    private void stok() {
        String stok = txt_stok.getText();

        DefaultTableModel LaporanStok = new DefaultTableModel();
        LaporanStok.addColumn("code Prod");
        LaporanStok.addColumn("NomProd");
        LaporanStok.addColumn("quent");

        try {
            String cari = "CALL Product_less_then('" + stok + "');";
            resultSet = statement.executeQuery(cari);

            boolean dataFound = false;

            while (resultSet.next()) {
                dataFound = true;
                LaporanStok.addRow(new Object[]{
                    resultSet.getString("productcode"),
                    resultSet.getString("productname"),
                    resultSet.getString("quantity")
                });
            }

            if (dataFound) {
                tb_stok.setModel(LaporanStok);
            } else {
                // Jika tidak ada data ditemukan, kosongkan tabel
                LaporanStok.setRowCount(0);
                tb_stok.setModel(LaporanStok);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cek kembali " + e + "");
        }
    }

    private void terlaris() {
        String favorit = txt_terlaris.getText();

        DefaultTableModel LaporanLaris = new DefaultTableModel();
        LaporanLaris.addColumn("code Prod");
        LaporanLaris.addColumn("nomProd");
        LaporanLaris.addColumn("PrxVnt");

        try {
            String cari = "CALL TopProduct('" + favorit + "');";
            resultSet = statement.executeQuery(cari);

            boolean dataFound = false;

            while (resultSet.next()) {
                dataFound = true;
                LaporanLaris.addRow(new Object[]{
                    resultSet.getString("productcode"),
                    resultSet.getString("productname"),
                    resultSet.getString("sellprice")
                });
            }

            if (dataFound) {
                tb_favorit.setModel(LaporanLaris);
            } else {
                // Jika tidak ada data ditemukan, kosongkan tabel
                LaporanLaris.setRowCount(0);
                tb_favorit.setModel(LaporanLaris);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cek kembali " + e + "");
        }
    }

    private void tampilLaporan() {
        try {
            String tampilBarang = "SELECT * FROM salleraport WHERE date = CURRENT_DATE;";
            resultSet = statement.executeQuery(tampilBarang);

            DefaultTableModel laporan = new DefaultTableModel();
            laporan.addColumn("id");
            laporan.addColumn("total");
            laporan.addColumn("vendeur");

            laporan.getDataVector().removeAllElements();
            laporan.fireTableDataChanged();
            laporan.setRowCount(0);

            while (resultSet.next()) {
                laporan.addRow(new Object[]{
                    resultSet.getString("salesid"),
                    resultSet.getString("total_paye"),
                    resultSet.getString("soldby")
                });
                tb_laporan.setModel(laporan);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "cek Kembali " + e + "");
        }
    }
//////////////////////////////////////

    private String getCureentTime() {
//        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date dates = new Date();
        // System.out.println(dateFormat.format(jDateChooser1.getDate()));

        return dateFormat.format(dates);

    }

    private void totalPenjualan() {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//            String tanggalPenjualan = dateFormat.format(getCureentTime());

            String jumlahPenjualan = "CALL SaleAmount('" + getCureentTime() + "', @JumlahPenjualan);";
            String selectJumlahPenjualan = "SELECT @JumlahPenjualan;";

            // Eksekusi perintah CALL JumlahPenjualan
            statement.executeQuery(jumlahPenjualan);
            resultSet = statement.executeQuery(selectJumlahPenjualan);

            // Eksekusi perintah SELECT untuk mengambil nilai @JumlahPenjualan
            if (resultSet.next()) {
                lb_totalTodaySales.setText(Integer.toString(resultSet.getInt(1)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Periksa kembali " + e.getMessage());
        }
    }

    private void totalKeuntungan() {

        try {
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//            String tanggalPenjualan = dateFormat.format(tanggal);

            String totalKeuntungan = "CALL BenfitToDay('" + getCureentTime() + "', @totalKeuntungan)";
            String selectTotalKeuntungan = "SELECT @totalKeuntungan;";

            // Eksekusi perintah CALL Keuntungan
            statement.executeQuery(totalKeuntungan);
            resultSet = statement.executeQuery(selectTotalKeuntungan);

            if (resultSet.next()) {
                lb_totalTodayBenefice.setText(Integer.toString(resultSet.getInt(1)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Periksa kembali " + e.getMessage());
        }
    }

    private void totalPendapatan() {

        try {
            conn = new ConnectionFactory().getConn();
            statement = conn.createStatement();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        try {
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//            String tanggalPenjualan = dateFormat.format(tanggal);

            String totalPendapatan = "CALL TotalPayee('" + getCureentTime() + "', @totalHargaPenjualan)";
            String selectTotalPendapatan = "SELECT @totalHargaPenjualan;";
            statement.executeQuery(totalPendapatan);
            resultSet = statement.executeQuery(selectTotalPendapatan);

            if (resultSet.next()) {
                lb_TotalRevenue.setText(Integer.toString(resultSet.getInt(1)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Periksa kembali " + e.getMessage());
        }
    }

}
